### ISSUE TITLE
need a tag for release 0.3

### ISSUE THREAD

**Issue by rleungx** [pingcap/fail-rs#31]
**Describe the bug**
From the README, the version has already bumped to 0.3. But in https://crates.io/crates/fail, its version is still 0.2.1. I guess we need a tag for release 0.3?

**To Reproduce**

**Expected behavior**

**System information**

**Additional context**

**Comment by BusyJay** [comment]
Should remove appveyor icon from readme before releasing.

**Comment by Hoverbear** [comment]
Hi @BusyJay , seems you're the only one who can publish a new release: https://crates.io/crates/fail

**Comment by lucab** [comment]
@BusyJay I think that at this point we cleared the queue of all pending PRs with breaking API changes. It would be good to tag + publish a `0.3.0` version now.

**Comment by BusyJay** [comment]
Sure. Thanks for your help!

**Comment by BusyJay** [comment]
Now it's released!
