### ISSUE TITLE
crater fails to test fail-rs

### ISSUE THREAD

**Issue by brson** [pingcap/fail-rs#36]
I just noticed in a crater run that fail-rs is broken: https://crater-reports.s3.amazonaws.com/pr-60466/master%237840a0b753a065a41999f1fb6028f67d33e3fdd5/reg/fail-0.2.1/log.txt

It doesn't _look_ like a problem with the crate, but I've asked @pietroalbini about it. Would be nice to have fail tested properly by crater.

**Comment by pietroalbini** [comment]
That's an internal crater error, not a crate error.

**Comment by brson** [comment]
Seem so have been spurious. Thanks for the investigation @pietroalbini!
