### ISSUE TITLE
API docs mention `no_fail` feature

### ISSUE THREAD

**Issue by brson** [pingcap/fail-rs#39]
The API docs mention the `no_fail` feature, but that feature no longer exists. Instead the API docs should mention, probably near the top, that failpoints are not active unless the `failpoints` feature is on, and its existence can be checked (after https://github.com/pingcap/fail-rs/pull/38) statically or dynamically with `has_failpoints`.

cc @lucab

**Comment by lucab** [comment]
Git master has no occurrences of `no_fail`, so I think you are looking at docs.rs, where 0.2.1 is still the freshest version (see https://github.com/pingcap/fail-rs/pull/37#issuecomment-501606095).

Regarding enhancing doc, the feature and code generation behavior is documented under "Usage considerations". I agree that such section unfortunately follows a huge wall of text, so it isn't very visible.

**Comment by brson** [comment]
Ah you are right. Thanks for the correction.
